name: Morning Discord Message

permissions:
  contents: write
  
on:
  schedule:
    - cron: "*/5 * * * *"   # every 5 minutes
  # Allows you to manually trigger the workflow from the GitHub Actions tab
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install requests
        run: pip install requests pytz

      - name: Run script
        run: python script.py
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit state file
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add last_sent.txt
          git commit -m "Update last sent state" || echo "No changes"
          git push
